PUT http://localhost:3000/user/1
Content-Type: application/json
Accept: application/json

{
  "userUpdate": {
    "non_liquid_assets": 5000,
    "liquid_assets": 2000,
    "savings": 1500,
    "checking": 500,
    "debt": 1000,
    "monthly_income": 4000,
    "other_income": 500,
    "bonuses": 250
  }
}

###

PUT http://localhost:3000/budget/1/budgetAllocation
Content-Type: application/json

{
  "budgetAllocationUpdate": {
    "savings_ratio": 0.25,
    "investments_ratio": 0.5,
    "guilt_free_spending_ratio": 0.25
  }
}

###

PUT http://localhost:3000/budget/livingCosts/1
Content-Type: application/json

{
  "livingCostsUpdate": {
    "rent": 1200,
    "bills": 200,
    "insurance": 150,
    "transportation": 100,
    "debt_payments": 300,
    "groceries": 400,
    "buffer_percent": 0.1
  }
}

###

PUT http://localhost:3000/savingFunds/1
Content-Type: application/json

{
  "savingFundsUpdate": {
    "emergency_fund_ratio": 0.6,
    "vacation_fund_ratio": 0.2,
    "gifts_fund_ratio": 0.2
  }
}

###

